path: C:/Users/Yasins/Desktop/UAV/splitted_dataset

train: images/train # relative to path
val: images/val # relative to path
test: images/test # relative to path

# Number of classes
nc: 1

# Class names
names: ['UAV']